on:
  push:
    branches: [master]
  pull_request:
name: security

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: ${{ vars.GO_VERSION || '1.24.12' }}
        go-package: ./...
